### ISSUE TITLE
2.1 System Overview

### ISSUE THREAD

**Issue by DIBASHGH1** [Group-S1-Tech-Domain/Mid-Project-Deliverables#10]

**Comment by Emmanuel8848** [comment]
The presentation layer, the application layer, and the data layer represent the system architecture. The user interface and interaction between the user and the system will be handled by the presentation layer. The business logic will be included in the application layer, which will manage the processing of user requests. The data layer will store and handle all system-related data.

**Comment by Ashokkc33** [comment]
The system architecture of Australian Clinical Labs Online Reporting system consists of overall design of the system, which includes it's physical and logical components, and how they interact with one another to meet the system's aims and work according to functionality. This portion will give an overview of the system architecture and its components.
The Australian Clinical Labs Online Reporting System is a web-based application whose main aim is to give patients and medical practitioners with a secure and trustworthy platform in today's generation to access their medical information online. This system will be hosted on a web server and will be available to authorized users using a web browser
