### ISSUE TITLE
2.4Software Components

### ISSUE THREAD

**Issue by DIBASHGH1** [Group-S1-Tech-Domain/Mid-Project-Deliverables#13]

**Comment by Emmanuel8848** [comment]
To implement this system, the following software components will be required:

•	Web server software (for example, Apache)
•	Database management system (for example, MySQL , SQL Server)
•	Programming languages (for example, HTML, CSS, JavaScript, and PHP)
The software components used to operate the system have an importance to the successful operation of the Australian Clinical Labs Online Reporting System. The operating system offers a solid and secure base for the system to run on. The web server in use is Apache HTTP Server, which is a dependable and efficient tool for managing online requests and serving web pages to users.
MySQL Server is a data storage and management technology. It was created to be reliable and capable of growing as the amounts of data grow. The system operates by connecting to the database server using SQL (Structured Query Language), making it effective in data retrieval and administration activities.
 HTML, CSS, JavaScript, and PHP are some of the programming languages that is used by this system. HTML and CSS are used to build the user interface as well as define the layout and style of web pages. JavaScript is used to give interaction and dynamic behavior to the system, such as form validation and real-time changes. PHP is used for server-side allowing the system to conduct backend operations and interface with the database server.

**Comment by rakeshGiri123** [comment]
Software Components
 To implement this system, the following software components will be required:

•	Web server software (for example, Apache)
•	Database management system (for example, MySQL , SQL Server)
•	Programming languages (for example, HTML, CSS, JavaScript, and PHP)
The software components used to operate the system have an importance to the successful operation of the Australian Clinical Labs Online Reporting System. The operating system offers a solid and secure base for the system to run on. The web server in use is Apache HTTP Server, which is a dependable and efficient tool for managing online requests and serving web pages to users.
MySQL Server is a data storage and management technology. It was created to be reliable and capable of growing as the amounts of data grow. The system operates by connecting to the database server using SQL (Structured Query Language), making it effective in data retrieval and administration activities.
 HTML, CSS, JavaScript, and PHP are some of the programming languages that is used by this system. HTML and CSS are used to build the user interface as well as define the layout and style of web pages. JavaScript is used to give interaction and dynamic behavior to the system, such as form validation and real-time changes. PHP is used for server-side allowing the system to conduct backend operations and interface with the database server.
