### ISSUE TITLE
2.5 Logical view of the system

### ISSUE THREAD

**Issue by DIBASHGH1** [Group-S1-Tech-Domain/Mid-Project-Deliverables#15]

**Comment by Emmanuel8848** [comment]
[
![Logical View of system](https://github.com/Group-S1-Tech-Domain/Mid-Project-Deliverables/assets/130024508/df69d0ed-9fcd-49b7-a331-d6f85304043c)
](url)

**Comment by Emmanuel8848** [comment]
![Logical View of system](https://github.com/Group-S1-Tech-Domain/Mid-Project-Deliverables/assets/130024508/3d1d9a61-061c-4ce9-8f5c-12150ffcfc4d)

**Comment by Emmanuel8848** [comment]
[logical view of system.docx](https://github.com/Group-S1-Tech-Domain/Mid-Project-Deliverables/files/11503282/logical.view.of.system.docx)
