### ISSUE TITLE
2.6 Functional view of the system

### ISSUE THREAD

**Issue by DIBASHGH1** [Group-S1-Tech-Domain/Mid-Project-Deliverables#16]

**Comment by Prem49B** [comment]
![Image](https://user-images.githubusercontent.com/130022474/236972611-fd7b5d20-8711-4706-806c-1184f7258ff2.jpeg)



![Image](https://user-images.githubusercontent.com/130022474/236972643-20827753-20cb-4842-8f64-ba3ffbd52676.jpeg)

**Comment by Prem49B** [comment]
Functional view for appointment
![Image](https://user-images.githubusercontent.com/130022474/236974241-0c519479-dfe6-4070-bb8c-d76c0c73f75f.jpeg)

Functional  view for user login

![Image](https://user-images.githubusercontent.com/130022474/236974401-d542ae8e-6cf1-43a6-a2e1-b1a558f63d87.jpeg)

**Comment by Prem49B** [comment]
![Image](https://github.com/Group-S1-Tech-Domain/Mid-Project-Deliverables/assets/130022474/511df201-94b3-4250-aa08-013774d7382f)
![Image](https://github.com/Group-S1-Tech-Domain/Mid-Project-Deliverables/assets/130022474/5230bd56-f5ad-4d71-b4b3-03e91dbdd6b8)
