### ISSUE TITLE
3.1 Final ERD

### ISSUE THREAD

**Issue by DIBASHGH1** [Group-S1-Tech-Domain/Mid-Project-Deliverables#17]

**Comment by Emmanuel8848** [comment]
[](
![ERD  Medical](https://github.com/Group-S1-Tech-Domain/Mid-Project-Deliverables/assets/130024508/c1d51411-d918-44ff-900c-bb47f9965253)
url)

**Comment by DIBASHGH1** [comment]
![Revised Final ERD]
