### ISSUE TITLE
4.0 User Interface Design

### ISSUE THREAD

**Issue by DIBASHGH1** [Group-S1-Tech-Domain/Mid-Project-Deliverables#19]

**Comment by Prem49B** [comment]
UI of viewing all appointments


![Image](https://github.com/Group-S1-Tech-Domain/Mid-Project-Deliverables/assets/130022474/585a4903-925e-41aa-a52e-98b8a2a6380e)

UI of creating services 


![Image](https://github.com/Group-S1-Tech-Domain/Mid-Project-Deliverables/assets/130022474/13073f5e-2856-4be7-82b1-f7cacbd95a1c)

UI of appointment details


![Image](https://github.com/Group-S1-Tech-Domain/Mid-Project-Deliverables/assets/130022474/02132501-c9c1-477b-ab39-190b0da9084e)

UI of payment


![Image](https://github.com/Group-S1-Tech-Domain/Mid-Project-Deliverables/assets/130022474/f0312688-2695-4047-867e-47787ea590f9)

UI of payment system admin


![Image](https://github.com/Group-S1-Tech-Domain/Mid-Project-Deliverables/assets/130022474/c3728824-ce62-4b22-93c3-95cdaa4e656b)
