### ISSUE TITLE
1.2 Non-Functional Requirements

### ISSUE THREAD

**Issue by DIBASHGH1** [Group-S1-Tech-Domain/Mid-Project-Deliverables#9]

**Comment by Aashish9999** [comment]
Non-Functional Requirement:
NFR NO.
Non-Functional Requirement
Components
Comments
NFR1
Performance
 
The system should be quick and responsive, with short load times.
NFR2
Security
 
The system should be secure and restrict unwanted access to user data.
NFR3
Usability
 
The system should be simple to use, with a straightforward user interface.
NFR4
Compatibility
 
Australian Clinical Labs Online Reporting System should work on various sets of devices and web browsers.

**Comment by Aashish9999** [comment]
Non-Functional Requirement:
NFR NO.
Non-Functional Requirement

NFR1
Performance
Components:
database query optimizations, Optimize Front-End Performance
Comments:
The system should be quick and responsive, with short load times.
NFR2
Security
Components:
Md5 security, Secure Login
Comments:
The system should be secure and restrict unwanted access to user data.
NFR3
Usability
Components:
Navigation bar, search functional, error messages, Forms, Consistent Design and Layout
Comments:
The system should be simple to use, with a straightforward user interface.
NFR4
Compatibility
Components:
Responsive Design,
All MySQL versions, all php versions
Comments:
Australian Clinical Labs Online Reporting System should work on various sets of devices and web browsers.
